spring:
  application:
    name: ms-autospare-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/autosparescm
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8041/eureka/

zuul:
  prefix: /autosparegateway
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  routes:
    orderprocessingservices:
      path: /orderprocessingservices/**
      url: ms-order-processing
      strip-prefix: false
    usermanagementservices:
      path: /usermanagementservices/**
      url: ms-user-management
      strip-prefix: false
    productmanagementservices:
      path: /productmanagementservices/**
      url: ms-product-management
      strip-prefix: false

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000