server:
  port: 8031
spring:
  application:
    name: ms-autospare-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/autosparescm
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false

zuul:
  prefix: /autosparegateway
  routes:
    orderprocessingservices:
      path: /orderprocessingservices/**
      url: http://localhost:8001/orderprocessingservices/
    usermanagementservices:
      path: /usermanagementservices/**
      url: http://localhost:8011/usermanagementservices/
    productmanagementservices:
      path: /productmanagementservices/**
      url: http://localhost:8021/productmanagementservices/

